name: Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * *'  # 07:00 Madrid invierno / 08:00 verano 

jobs:
  run:
    runs-on: ubuntu-latest 
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Python  
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'  
      - name: Debug path
        run: |
          pwd
          ls -R
      - name: Install system dependencies (GDAL)
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
      - name: Set GDAL environment variables
        run: |
          echo "GDAL_CONFIG=$(which gdal-config)" >> $GITHUB_ENV
          echo "GDAL_VERSION=$(gdal-config --version)" >> $GITHUB_ENV
          echo "CPLUS_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
          echo "USE_PYGEOS=0" >> $GITHUB_ENV
      - name: Install Python dependencies (FIX Fiona/GDAL)
        run: |
          pip install --upgrade pip setuptools wheel
      
          pip install numpy pandas shapely pyproj matplotlib requests
      
          # 🔥 CRÍTICO: forzar uso del GDAL del sistema
          pip install fiona --no-build-isolation --no-cache-dir --config-settings=--global-option=build_ext --config-settings=--global-option="-I/usr/include/gdal"
      
          pip install geopandas

      - name: Ejecutar pipeline
        run: python Unificar_SHP_de_incendios.py

      - name: Commit resultados
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/
          git diff --staged --quiet || git commit -m "Actualización diaria SHP"
          git push
